import type { Metadata } from 'next'
import { getSite } from '@/lib/site'
import { PrintButton } from '@/components/print-button'

export const metadata: Metadata = { title: 'Resume', description: '项目经历、能力方向与当前工作。' }

export default async function ResumePage() {
  const profile = await getSite()
  return <><div className="flex items-end justify-between gap-4"><div><h1 className="text-3xl font-semibold tracking-tight">{profile.identity.name} · Resume</h1><p className="mt-3 text-neutral-500">{profile.identity.role}</p><p className="mt-1 text-sm text-neutral-400">{profile.identity.location} · {profile.identity.status}</p></div><PrintButton /></div><section className="mt-12"><h2 className="text-sm font-semibold uppercase tracking-wider text-neutral-400">Current</h2><div className="mt-5 grid gap-3 sm:grid-cols-[140px_1fr]"><span className="text-sm text-neutral-400">2026 — Now</span><div><h3 className="font-medium">妙喵 · Creator Video Agent</h3><p className="mt-2 leading-7 text-neutral-500">{profile.product.finalGoal}</p><p className="mt-1 text-sm text-neutral-400">验证端点：先用我的个人网站、资料和视频跑通端到端体验。</p></div></div></section><section className="mt-14"><h2 className="text-sm font-semibold uppercase tracking-wider text-neutral-400">Education</h2><div className="mt-5 grid gap-3 sm:grid-cols-[140px_1fr]"><span className="text-sm text-neutral-400">2025 — 2028（计划）</span><div><h3 className="font-medium">宁波大学阳明学院 · 金融工程</h3><p className="mt-2 leading-7 text-neutral-500">大一已转专业到金融工程，计划大二修完全部学分，提前一年 2028 年毕业。短期准备暑假北京实习面试，中期目标是大三字节实习，长期目标是大学毕业创业 → 援助非洲。</p></div></div></section><section className="mt-14"><h2 className="text-sm font-semibold uppercase tracking-wider text-neutral-400">Selected experience</h2><div className="mt-5 space-y-8">{profile.projects.map((project) => <div key={project.id} className="grid gap-3 sm:grid-cols-[140px_1fr]"><span className="text-sm text-neutral-400">{project.stage}</span><div><h3 className="font-medium">{project.name}</h3><p className="mt-2 leading-7 text-neutral-500">{project.result}</p>{project.tags.length > 0 && <div className="mt-3 flex flex-wrap gap-1.5">{project.tags.map((tag) => <span key={tag} className="rounded-md bg-neutral-100 px-2 py-0.5 text-xs text-neutral-500">{tag}</span>)}</div>}</div></div>)}</div></section><section className="mt-14"><h2 className="text-sm font-semibold uppercase tracking-wider text-neutral-400">Contact</h2><div className="mt-5 grid gap-3 sm:grid-cols-[140px_1fr]"><span className="text-sm text-neutral-400">Public</span><div className="space-y-1.5">{profile.links.filter((l) => l.visibility === 'public').map((link) => <div key={link.label}><span className="text-neutral-400">{link.label}: </span><a href={link.href} target="_blank" rel="noreferrer" className="text-neutral-700 hover:text-neutral-950 hover:underline">{link.value}</a></div>)}</div></div></section><section className="mt-14"><h2 className="text-sm font-semibold uppercase tracking-wider text-neutral-400">Focus</h2><div className="mt-5 flex flex-wrap gap-2">{profile.identity.tags.map((tag) => <span key={tag} className="rounded-full border border-neutral-200 px-3 py-1.5 text-sm text-neutral-600">{tag}</span>)}</div></section></>
}
